# UPDATED 16.05.23 - 17:46
zuul:
  prefix: /api
  ignoredServices: "*"
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080

# Internationalization
spring.messages.basename: messages/messages

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
